language: node_js
node_js:
  - "stable"
cache:
  directories:
  - frontend/node_modules
  - backend/node_modules
script:
  - cd frontend
  - npm install
  - npm test
  - npm run build
  - cd ../backend
  - npm install
  - npm test
  - npm run build
