language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
  - backend/node_modules
script:
  - npm test
  - npm run build
  - cd backend
  - npm install
  - npm test
  - npm run build
